### PR TITLE
feat: improve Promise-compliance

### PR DESCRIPTION
**Pull request by jonaskuske**
FYI, got both the subclassed version and the standalone one (doesn't rely on `Promise` at all) to work!
Both pass your tests and the A+ test suite and I managed to get the types working, too :)

You can switch between the implementations by adjusting the commented exports at the bottom in `DeferredPromise.ts`, and run the tests with `npm test && npm run test-aplus`.

Give them a try and feel free to use them or to borrow stuff for your impl :)

### CODE REVIEW

**Comment by kettanaito** [comment]
This is truly impressive! Thank you so much for working on this.

I like the subclass implementation since we can rely on the native Promise that way. It'd be great if we could reuse/change the `createDeferredExecutor` function so it can be used standalone and also power the subclass. I will see if I can do that.

**Comment by kettanaito** [comment]
I rewrote it a bit to use a deferred executor. The tests are passing, I think it works as expected.

**Review by kettanaito — APPROVED** [review]
This looks fantastic! Thank you, @jonaskuske! 

Is there any way I can buy you a coffee?

**Comment by jonaskuske** [comment]
Thanks! Glad the integration with the external executor fn went so smoothly :)
(and thanks for the readme mention!)

As for ☕, there's [ko-fi](https://ko-fi.com/jonaskuske) or [paypal.me](https://www.paypal.me/jonaskuske), if you want 😊

**Pull request merged**
